name: Deploy Node App on Azure VM 

on:
  workflow_dispatch:

permissions:
  contents: read
  actions: read
  checks: write
  pull-requests: write
  id-token: write   # harmless here; not using OIDC in this workflow

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4.4.0
        with:
          node-version: 22.x
          cache: npm
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Build the application (optional)
        run: |
          npm run build 2>/dev/null || echo "No build script found, skipping build step"

      - name: Run unit tests with coverage and JUnit reports
        env:
          JEST_JUNIT_OUTPUT: coverage/junit.xml
        run: npm run test:ci

      - name: Publish test results to Checks
        uses: dorny/test-reporter@v2.1.1
        if: always()
        with:
          name: Jest Test Results
          path: coverage/junit.xml
          reporter: jest-junit
          fail-on-error: true

      - name: Upload test results to GitHub
        uses: actions/upload-artifact@v4.6.2
        if: always()
        with:
          name: test-results-node
          path: coverage/
          retention-days: 30

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v6.0.0
        env:
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=sample-node-app-saurabh
            -Dsonar.organization=sda
            -Dsonar.token=${{ secrets.SONAR_TOKEN }}
            -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }}
            -Dsonar.sources=.
            -Dsonar.exclusions=node_modules/**,coverage/**,tests/**,**/*.test.js,**/*.spec.js
            -Dsonar.tests=tests/
            -Dsonar.test.inclusions=**/*.test.js,**/*.spec.js
            -Dsonar.coverage.exclusions=node_modules/**,coverage/**,tests/**,**/*.test.js,**/*.spec.js

      - name: Create deployment package
        run: |
          set -euo pipefail
          STAGING="$GITHUB_WORKSPACE/deployment-package"
          rm -rf "$STAGING"
          mkdir -p "$STAGING"

          [ -d public ] && cp -r public "$STAGING/" || echo "No public/ directory found"
          [ -d node_modules ] && cp -r node_modules "$STAGING/" || echo "No node_modules/ directory found"
          [ -f server.js ] && cp server.js "$STAGING/" || echo "No server.js found"
          cp package.json "$STAGING/"
          cp package-lock.json "$STAGING/"
          [ -f README.md ] && cp README.md "$STAGING/" || true
          [ -f Dockerfile ] && cp Dockerfile "$STAGING/" || echo "No Dockerfile found"

          (cd "$STAGING" && npm pkg delete devDependencies || true)

          TS="$(date +%Y%m%d-%H%M%S)"
          SHORT_SHA="${GITHUB_SHA::7}"
          ZIP_NAME="deployment-package-${SHORT_SHA}-${TS}.zip"
          (cd "$GITHUB_WORKSPACE" && zip -r "$ZIP_NAME" "deployment-package")
          echo "ZIP_NAME=$ZIP_NAME" >> "$GITHUB_ENV"

      - name: Azure login (client secret)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}

      - name: Upload deployment package artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: deployment-package-node-${{ github.run_number }}
          path: ${{ env.ZIP_NAME }}
          retention-days: 90

      - name: Upload package to Blob (key-based, hardened)
        if: ${{ success() }}
        uses: azure/cli@v2.1.0
        env:
          ZIP_NAME: ${{ env.ZIP_NAME }}
          AZ_STORAGE_ACCOUNT: ${{ secrets.AZ_STORAGE_ACCOUNT }}
          AZ_STORAGE_CONTAINER: ${{ secrets.AZ_STORAGE_CONTAINER }}
          AZ_STORAGE_KEY: ${{ secrets.AZ_STORAGE_KEY }}
        with:
          inlineScript: |
            set -euo pipefail
            : "${AZ_STORAGE_ACCOUNT:?AZ_STORAGE_ACCOUNT missing}"
            : "${AZ_STORAGE_CONTAINER:?AZ_STORAGE_CONTAINER missing}"
            : "${AZ_STORAGE_KEY:?AZ_STORAGE_KEY missing}"
            : "${ZIP_NAME:?ZIP_NAME missing}"

            # Trim stray whitespace/newlines in key
            AZ_STORAGE_KEY="$(printf %s "$AZ_STORAGE_KEY" | tr -d '\r\n')"
            export AZ_STORAGE_KEY

            # Ensure container exists (idempotent)
            az storage container create \
              --name "$AZ_STORAGE_CONTAINER" \
              --account-name "$AZ_STORAGE_ACCOUNT" \
              --account-key "$AZ_STORAGE_KEY" \
              --only-show-errors 1>/dev/null

            # Quick preflight
            az storage blob list \
              --account-name "$AZ_STORAGE_ACCOUNT" \
              --account-key "$AZ_STORAGE_KEY" \
              --container-name "$AZ_STORAGE_CONTAINER" \
              --num-results 1 --only-show-errors 1>/dev/null

            echo "Uploading $ZIP_NAME ..."
            az storage blob upload \
              --account-name "$AZ_STORAGE_ACCOUNT" \
              --account-key "$AZ_STORAGE_KEY" \
              --container-name "$AZ_STORAGE_CONTAINER" \
              --file "$ZIP_NAME" \
              --name "$ZIP_NAME" \
              --overwrite true \
              --only-show-errors

            # Short-lived SAS URL for VM download
            SAS=$(az storage blob generate-sas \
              --account-name "$AZ_STORAGE_ACCOUNT" \
              --account-key "$AZ_STORAGE_KEY" \
              --container-name "$AZ_STORAGE_CONTAINER" \
              --name "$ZIP_NAME" \
              --permissions r \
              --expiry "$(date -u -d '+1 hour' '+%Y-%m-%dT%H:%MZ')" \
              --https-only --full-uri -o tsv)

            echo "::add-mask::$SAS"
            echo "PACKAGE_SAS_URL=$SAS" >> "$GITHUB_ENV"

      - name: Deploy on Azure VM (PM2 restart; Node/PM2 preinstalled)
        if: ${{ success() }}
        uses: azure/cli@v2.1.0
        env:
          AZURE_RESOURCE_GROUP: ${{ secrets.AZURE_RESOURCE_GROUP }}
          AZURE_VM_NAME: ${{ secrets.AZURE_VM_NAME }}
          PACKAGE_SAS_URL: ${{ env.PACKAGE_SAS_URL }}
          APP_USER: azureuser           # change if different
          APP_DIR: /opt/myapp
          APP_NAME: myapp
        with:
          inlineScript: |
            set -euo pipefail
            az vm run-command invoke \
              --resource-group "$AZURE_RESOURCE_GROUP" \
              --name "$AZURE_VM_NAME" \
              --command-id RunShellScript \
              --scripts "
                set -euo pipefail
                PACKAGE_SAS_URL='$PACKAGE_SAS_URL'
                APP_USER='${APP_USER:-azureuser}'
                APP_DIR='${APP_DIR:-/opt/myapp}'
                APP_NAME='${APP_NAME:-myapp}'
                RELEASES_DIR=\"\$APP_DIR/releases\"
                CURRENT_DIR=\"\$APP_DIR/current\"
                TMP=/tmp
                ZIP_FILE=\$TMP/\$(basename \"\$PACKAGE_SAS_URL\" | cut -d'?' -f1)

                echo '==> Prepare directories'
                sudo mkdir -p \"\$RELEASES_DIR\" \"\$CURRENT_DIR\"
                sudo chown -R \"\$APP_USER\":\"\$APP_USER\" \"\$APP_DIR\"

                echo '==> Download deployment package'
                curl -fSL \"\$PACKAGE_SAS_URL\" -o \"\$ZIP_FILE\"

                TS=\$(date +%Y%m%d-%H%M%S)
                DEST_DIR=\"\$RELEASES_DIR/\$TS\"
                mkdir -p \"\$DEST_DIR\"

                echo '==> Unzip package'
                unzip -o \"\$ZIP_FILE\" -d \"\$DEST_DIR\"

                # Flatten if the zip has a root 'deployment-package/' folder
                if [ -d \"\$DEST_DIR/deployment-package\" ]; then
                  shopt -s dotglob
                  mv \"\$DEST_DIR\"/deployment-package/* \"\$DEST_DIR\"/
                  rm -rf \"\$DEST_DIR\"/deployment-package
                  shopt -u dotglob
                fi

                sudo chown -R \"\$APP_USER\":\"\$APP_USER\" \"\$DEST_DIR\"

                echo '==> Install production dependencies (if package.json exists)'
                if [ -f \"\$DEST_DIR/package.json\" ]; then
                  sudo -u \"\$APP_USER\" bash -lc \"cd '\$DEST_DIR' && (npm ci --omit=dev || npm i --omit=dev)\"
                fi

                echo '==> Point current -> new release'
                ln -sfn \"\$DEST_DIR\" \"\$CURRENT_DIR\"

                echo '==> Start/Restart with PM2'
                if pm2 describe \"\$APP_NAME\" >/dev/null 2>&1; then
                  sudo -u \"\$APP_USER\" pm2 restart \"\$APP_NAME\"
                else
                  if [ -f \"\$CURRENT_DIR/package.json\" ] && grep -q '\"start\"' \"\$CURRENT_DIR/package.json\"; then
                    sudo -u \"\$APP_USER\" pm2 start npm --name \"\$APP_NAME\" -- start --prefix \"\$CURRENT_DIR\"
                  elif [ -f \"\$CURRENT_DIR/server.js\" ]; then
                    sudo -u \"\$APP_USER\" pm2 start \"\$CURRENT_DIR/server.js\" --name \"\$APP_NAME\"
                  else
                    echo 'No start script in package.json and no server.js found.' >&2
                    exit 1
                  fi
                fi

                echo '==> Save PM2 process list'
                sudo -u \"\$APP_USER\" pm2 save

                echo '==> PM2 list'
                sudo -u \"\$APP_USER\" pm2 ls || true

                echo '==> Done'
              "
